version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
      - run:
          name: Build Docker Image
          command: |
            cd services/notes_service
            USERNAME=$(echo "$GHCR_USERNAME" | tr "[:upper:]" "[:lower:]")
            IMAGE_NAME="ghcr.io/$USERNAME/just_put_it_notes_service"
            docker build -t $IMAGE_NAME:${CIRCLE_SHA1} .
            docker tag $IMAGE_NAME:${CIRCLE_SHA1} $IMAGE_NAME:latest
      - run:
          name: Authenticate with GHCR
          command: |
            echo $GHCR_PAT | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
      - run:
          name: Push Docker Image to GHCR
          command: |
            IMAGE_NAME="ghcr.io/$USERNAME/just_put_it_notes_service"
            docker push $IMAGE_NAME:${CIRCLE_SHA1}
            docker push $IMAGE_NAME:latest

workflows:
  main-workflow:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
