image:
  repository: ghcr.io/estifen14/just_put_it_notes_service
  tag: "latest"

postgresql:
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
  fullnameOverride: postgres-service
  auth:
    postgresPassword: postgres
    database: just_put_it
  primary:
    persistence:
      enabled: false # Local-only setting
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 250m
        memory: 512Mi