apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/just_put_it
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
