spring.application.name=notes_service
spring.datasource.url=jdbc:postgresql://localhost:5432/just_put_it
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
