# 1. Create the ServiceAccount for ESO in the note-service-dev namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: note-service-eso-sa
  namespace: note-service-dev

---
# 2. Define the SecretStore connecting ESO to OpenBao
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-store
  namespace: note-service-dev
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "note-service-eso-role" # OpenBao role
          serviceAccountRef:
            name: "note-service-eso-sa"
            audiences:
              - "vault"
